name: alerttext
base: core22
version: '0.2'
summary: &_desc A really cool flutter snap that has TEXT BOXES in ALERT WIDGETS!
description: *_desc
grade: stable
confinement: strict

parts:
  alerttext:
    plugin: flutter
    source: alerttext

apps:
  alerttext:
    command: alerttext
    extensions: [gnome]

